var monsterdata={};
//難易度・優しい
//img=path
//name=名前
//attack=攻撃力
//guard=防御力
//xp=経験値（貰える数）
//magic=魔法（ない場合はnone）
monsterdata.easy=[
    {
        "img":'/img/monster/easy/slime.png',
        "name":'スライム',
        "attack":5,
        "guard":5,
        "hp":20,
        "xp":10,
        "magic":'none'
    },
    {
        "img":'/img/monster/easy/flower_spirit.png',
        "name":'花の精霊',
        "attack":8,
        "guard":8,
        "hp":30,
        "xp":15,
        "magic":'none'
    },
];
monsterdata.midium=[];
monsterdata.hard=[];